@TandemHostName = https://tdcservices.tandemdiabetes.com

POST {{TandemHostName}}/cloud/oauth2/token
Authorization: {{AuthorizationHeader}}
Content-Type: application/x-www-form-urlencoded
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

grant_type={{grant_type}}&scope={{scope}}&username={{username}}&password={{password}}

###